In [10]:
import cv2
import numpy
im_g = cv2.imread("smallgray.png",0)
ims = numpy.vstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
